drop table T_EMPLOYEE if exists;

create table T_EMPLOYEE (ID bigint identity primary key,NAME VARCHAR(45),DATE_OF_JOINING TIMESTAMP NOT NULL,SALARY decimal(8,2),EMAIL_ID VARCHAR(45),COUNTRY VARCHAR(45));

ALTER TABLE T_EMPLOYEE ALTER COLUMN SALARY SET DEFAULT 0.0;